// Generated by `voltmod schemagen`. Do not edit.

#pragma once

#include <VoltMod/Schema/Generated/CBaseAnimGraph.hpp>
#include <VoltMod/Schema/Generated/CBaseCombatCharacter.hpp>
#include <VoltMod/Schema/Generated/CBaseEntity.hpp>
#include <VoltMod/Schema/Generated/CBaseModelEntity.hpp>
#include <VoltMod/Schema/Generated/CBasePlayerController.hpp>
#include <VoltMod/Schema/Generated/CBasePlayerPawn.hpp>
#include <VoltMod/Schema/Generated/CBodyComponent.hpp>
#include <VoltMod/Schema/Generated/CCSCustomHudLayout.hpp>
#include <VoltMod/Schema/Generated/CCSCustomHudLayoutState.hpp>
#include <VoltMod/Schema/Generated/CCSPlayerController.hpp>
#include <VoltMod/Schema/Generated/CCSPlayerController_InGameMoneyServices.hpp>
#include <VoltMod/Schema/Generated/CCSPlayerPawn.hpp>
#include <VoltMod/Schema/Generated/CCSPlayerPawnBase.hpp>
#include <VoltMod/Schema/Generated/CEntityComponent.hpp>
#include <VoltMod/Schema/Generated/CEntityInstance.hpp>
#include <VoltMod/Schema/Generated/CGameSceneNode.hpp>
#include <VoltMod/Schema/Generated/CInButtonState.hpp>
#include <VoltMod/Schema/Generated/CModelState.hpp>
#include <VoltMod/Schema/Generated/CPlayerControllerComponent.hpp>
#include <VoltMod/Schema/Generated/CPlayerPawnComponent.hpp>
#include <VoltMod/Schema/Generated/CPlayer_ItemServices.hpp>
#include <VoltMod/Schema/Generated/CPlayer_MovementServices.hpp>
#include <VoltMod/Schema/Generated/CPlayer_ObserverServices.hpp>
#include <VoltMod/Schema/Generated/CPlayer_WeaponServices.hpp>
#include <VoltMod/Schema/Generated/CSkeletonInstance.hpp>
#include <VoltMod/Schema/Generated/CVoteController.hpp>
#include <VoltMod/Schema/Generated/CountdownTimer.hpp>
#include <VoltMod/Schema/Generated/Enums.hpp>
#include <VoltMod/Schema/Layout.hpp>
#include <VoltMod/Schema/Notify.hpp>
#include <VoltMod/Schema/View.hpp>
