"""Generate the C++ schema accessor layer from a schema dump and a manifest.

The dump comes from the `schema_dump` console command (tools/schema-dump). This turns the
classes and fields the manifest names into plain C++ with the offsets baked in, plus the layout
table the load-time verifier compares against the live schema.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Annotated, Any

import typer

from voltmod.tools import die, run_tool

app = typer.Typer(help="Generate the schema accessor layer.")

HEADER_DIR = Path("include/VoltMod/Schema")
# Generated headers sit in their own directory so what is hand-written is obvious.
GENERATED_DIR = HEADER_DIR / "Generated"
SOURCE_DIR = Path("src/Schema")
GENERATED_SRC_DIR = SOURCE_DIR / "Generated"
SCHEMA_DIR = Path("schema")

BANNER = "// Generated by `voltmod schemagen`. Do not edit.\n"

# The entity root: a class reaching this by inheritance replicates through the entity itself.
ENTITY_ROOT = "CEntityInstance"

BUILTINS = {
    "bool": "bool",
    "char": "char",
    "int8": "int8_t",
    "uint8": "uint8_t",
    "int16": "int16_t",
    "uint16": "uint16_t",
    "int32": "int32_t",
    "uint32": "uint32_t",
    "int64": "int64_t",
    "uint64": "uint64_t",
    "float32": "float",
    "float64": "double",
}

# Atomic types the engine treats as values. Anything not named here is skipped rather than
# guessed at, so an unmapped type is visible in the generated output instead of silently wrong.
ATOMIC_VALUES = {
    "Vector": "Vector",
    "VectorWS": "Vector",
    "QAngle": "QAngle",
    "Color": "uint32_t",
    "CPlayerSlot": "int32_t",
    "CEntityIndex": "int32_t",
    "CUtlSymbolLarge": "const char*",
    "CUtlString": "const char*",
    "GameTime_t": "float",
    "GameTick_t": "int32_t",
}

# Hungarian prefixes stripped from a field name to get its accessor. Only these, and only when
# an uppercase letter follows, so `m_lifeState` keeps its name instead of becoming `State`.
PREFIXES = {
    "a", "ang", "arr", "b", "cl", "clr", "d", "e", "f", "fl", "fn", "h", "i", "isz", "m",
    "n", "nv", "p", "pp", "psz", "pv", "q", "s", "str", "sz", "t", "u", "ub", "ui", "un",
    "v", "vec", "w", "x", "y", "z",
}


@dataclass
class Member:
    """One manifest field resolved against the dump."""

    schema_name: str
    accessor: str
    offset: int
    size: int
    kind: str  # value | enum | view | handle | chars | array | raw | skipped
    cpp: str = ""  # the C++ type for value/enum/handle/array element
    view: str = ""  # the schema class for a view
    embedded: bool = False  # a view held by value rather than behind a pointer
    extent: int = 0
    note: str = ""  # schema type spelling, for the offset comment
    skip_reason: str = ""


@dataclass
class Klass:
    """One generated class."""

    name: str
    size: int
    chain_offset: int
    base: str | None
    entity_rooted: bool = False
    embeds_in_entity: bool = False
    members: list[Member] = field(default_factory=list)

    @property
    def writable(self) -> bool:
        """Whether a write on this class has a route to the engine's dirty tracking."""
        return self.entity_rooted or self.chain_offset >= 0 or self.embeds_in_entity


def accessor_name(schema_name: str) -> str:
    """`m_flVelocityModifier` -> `VelocityModifier`. Raises when nothing usable is left."""
    body = schema_name.removeprefix("m_")
    if not body:
        raise ValueError(f"{schema_name}: no name left after m_")

    for size in (3, 2, 1):
        prefix, rest = body[:size], body[size:]
        if prefix in PREFIXES and rest[:1].isupper() and len(rest) >= 3:
            return rest

    if body[0].islower():
        return body[0].upper() + body[1:]
    return body


def parse_entry(entry: str) -> tuple[str, str | None, str | None]:
    """Split a manifest field entry into (schema name, accessor override, C++ type override)."""
    name, _, cpp = entry.partition(":")
    name, _, rename = name.partition(">")
    return name, rename or None, cpp or None


def bases_of(dump: dict[str, Any], name: str) -> list[str]:
    """The single-inheritance chain above @p name, nearest first."""
    chain: list[str] = []
    current = name
    while True:
        klass = dump["classes"].get(current)
        if not klass or not klass["bases"]:
            return chain
        current = klass["bases"][0]["name"]
        if current in chain:  # defensive: a cycle would hang the walk
            return chain
        chain.append(current)


def describe(entry: str, raw: dict[str, Any], dump: dict[str, Any]) -> Member:
    """Turn one dump field into a generated member, or mark it skipped."""
    schema_name, rename, cpp_override = parse_entry(entry)
    accessor = rename or accessor_name(schema_name)
    kind = raw["type"]
    common = {
        "schema_name": schema_name,
        "accessor": accessor,
        "offset": raw["offset"],
        "size": raw["size"],
        "note": kind["name"],
    }

    if cpp_override:
        return Member(**common, kind="value", cpp=cpp_override)

    category = kind["category"]
    if category == "builtin":
        mapped = BUILTINS.get(kind["name"])
        if not mapped:
            return Member(**common, kind="skipped", skip_reason=kind["name"])
        return Member(**common, kind="value", cpp=mapped)

    if category == "declared_enum":
        return Member(**common, kind="enum", cpp=kind["name"])

    if category == "declared_class":
        if kind["name"] not in dump["classes"]:
            return Member(**common, kind="skipped", skip_reason=kind["name"])
        return Member(**common, kind="view", view=kind["name"], embedded=True)

    if category == "pointer":
        inner = kind.get("inner", "")
        if inner not in dump["classes"]:
            return Member(**common, kind="skipped", skip_reason=kind["name"])
        return Member(**common, kind="view", view=inner)

    if category == "fixed_array":
        inner = kind.get("inner", "")
        extent = int(kind.get("extent", 0))
        if inner == "char":
            return Member(**common, kind="chars", extent=extent)
        mapped = BUILTINS.get(inner)
        if not mapped or extent <= 0:
            return Member(**common, kind="skipped", skip_reason=kind["name"])
        return Member(**common, kind="array", cpp=mapped, extent=extent)

    if category == "bitfield":
        # v1 has no bitfield accessor; the name already carries the width.
        return Member(**common, kind="skipped", skip_reason=kind["name"])

    if category == "atomic":
        atomic = kind.get("atomic")
        if atomic == "collection_of_t":
            # A CUtlVector's element handling is the consumer's business; bake the offset and
            # hand back the address so no SDK container type reaches a generated header.
            return Member(**common, kind="raw")
        if atomic == "t" and kind.get("name", "").startswith("CHandle"):
            return Member(**common, kind="handle", cpp="uint32_t")
        mapped = ATOMIC_VALUES.get(kind["name"])
        if mapped:
            return Member(**common, kind="value", cpp=mapped)
        return Member(**common, kind="skipped", skip_reason=kind["name"])

    return Member(**common, kind="skipped", skip_reason=f"{category} {kind['name']}")


def build_classes(dump: dict[str, Any], manifest: dict[str, Any]) -> dict[str, Klass]:
    """Resolve every manifest class, plus the bases and inner types they pull in."""
    wanted: dict[str, Any] = dict(manifest["classes"])
    classes: dict[str, Klass] = {}

    # Bases must exist as generated types so the C++ inheritance matches the schema's.
    pending = list(wanted)
    while pending:
        name = pending.pop()
        for base in bases_of(dump, name):
            if base not in wanted:
                wanted[base] = []
                pending.append(base)

    for name, entries in wanted.items():
        raw = dump["classes"].get(name)
        if raw is None:
            die(f"manifest names class '{name}', which the dump does not have")

        by_name = {f["name"]: f for f in raw["fields"]}
        chain = bases_of(dump, name)
        klass = Klass(
            name=name,
            size=raw["size"],
            chain_offset=raw["chain_offset"],
            base=chain[0] if chain else None,
            entity_rooted=name == ENTITY_ROOT or ENTITY_ROOT in chain,
        )

        selected = [f["name"] for f in raw["fields"]] if entries == "*" else list(entries)
        for entry in selected:
            schema_name, _, _ = parse_entry(entry)
            found = by_name.get(schema_name)
            if found is None:
                die(f"manifest names {name}::{schema_name}, which the dump does not have")
            klass.members.append(describe(entry, found, dump))

        seen: dict[str, str] = {}
        for member in klass.members:
            if member.accessor in seen:
                die(
                    f"{name}: '{member.schema_name}' and '{seen[member.accessor]}' both map to "
                    f"{member.accessor}(); rename one with '>' in the manifest"
                )
            seen[member.accessor] = member.schema_name

        classes[name] = klass

    # Views a member returns must be generated too, so pull them in and repeat.
    while True:
        missing = {
            m.view
            for k in classes.values()
            for m in k.members
            if m.kind == "view" and m.view not in classes
        }
        if not missing:
            break
        for name in missing:
            raw = dump["classes"][name]
            chain = bases_of(dump, name)
            classes[name] = Klass(
                name=name,
                size=raw["size"],
                chain_offset=raw["chain_offset"],
                base=chain[0] if chain else None,
                entity_rooted=name == ENTITY_ROOT or ENTITY_ROOT in chain,
            )
            for base in chain:
                if base not in classes:
                    raw_base = dump["classes"][base]
                    base_chain = bases_of(dump, base)
                    classes[base] = Klass(
                        name=base,
                        size=raw_base["size"],
                        chain_offset=raw_base["chain_offset"],
                        base=base_chain[0] if base_chain else None,
                        entity_rooted=base == ENTITY_ROOT or ENTITY_ROOT in base_chain,
                    )

    # A struct embedded by value replicates through whatever holds it, so it may only expose
    # setters when every holder is itself entity-rooted.
    holders: dict[str, list[str]] = {}
    for klass in classes.values():
        for member in klass.members:
            if member.kind == "view" and member.embedded:
                holders.setdefault(member.view, []).append(klass.name)
    for name, owners in holders.items():
        classes[name].embeds_in_entity = all(classes[o].entity_rooted for o in owners)

    return classes


def collect_enums(dump: dict[str, Any], classes: dict[str, Klass]) -> dict[str, Any]:
    """Every enum a generated member returns."""
    names = {m.cpp for k in classes.values() for m in k.members if m.kind == "enum"}
    out = {}
    for name in sorted(names):
        found = dump["enums"].get(name)
        if found is None:
            die(f"a generated field returns enum '{name}', which the dump does not have")
        out[name] = found
    return out


def enum_underlying(size: int) -> str:
    return {1: "int8_t", 2: "int16_t", 4: "int32_t", 8: "int64_t"}.get(size, "int32_t")


def cpp_identifier(name: str) -> str:
    """A schema name usable as a C++ identifier (`CFuncMover::Move_t` is nested in schema)."""
    return name.replace("::", "_")


def sorted_classes(classes: dict[str, Klass]) -> list[Klass]:
    return [classes[name] for name in sorted(classes)]


def member_signature(member: Member) -> list[str]:
    """The declarations one member contributes to a class body."""
    name = member.accessor
    if member.kind == "skipped":
        return [f"// skipped: {member.schema_name} ({member.skip_reason})"]
    if member.kind == "value" or member.kind == "handle":
        return [f"{member.cpp} {name}() const;"]
    if member.kind == "enum":
        return [f"{cpp_identifier(member.cpp)} {name}() const;"]
    if member.kind == "view":
        return [f"{member.view} {name}() const;"]
    if member.kind == "chars":
        return [f"std::string_view {name}() const;"]
    if member.kind == "array":
        return [f"{member.cpp} {name}(size_t index) const;"]
    if member.kind == "raw":
        return [f"void* {name}() const;"]
    raise AssertionError(member.kind)


def member_setters(member: Member) -> list[str]:
    """The setter declarations one member contributes, if it takes one."""
    name = member.accessor
    if member.kind in ("value", "handle"):
        return [f"void Set{name}({member.cpp} value) const;"]
    if member.kind == "enum":
        return [f"void Set{name}({cpp_identifier(member.cpp)} value) const;"]
    if member.kind == "chars":
        return [f"void Set{name}(std::string_view value) const;"]
    if member.kind == "array":
        return [f"void Set{name}(size_t index, {member.cpp} value) const;"]
    # A view, a raw collection address and a skipped field are never assigned wholesale.
    return []


def emit_header(klass: Klass, classes: dict[str, Klass]) -> str:
    """One `include/VoltMod/Schema/<Class>.hpp`."""
    includes = {"<VoltMod/Schema/View.hpp>"}
    if klass.base:
        includes.add(f"<VoltMod/Schema/Generated/{klass.base}.hpp>")
    needs_std = False
    for member in klass.members:
        if member.kind == "view":
            includes.add(f"<VoltMod/Schema/Generated/{member.view}.hpp>")
        if member.kind == "enum":
            includes.add("<VoltMod/Schema/Generated/Enums.hpp>")
        if member.kind == "chars":
            includes.add("<VoltMod/Core/CharBuf.hpp>")
            includes.add("<string_view>")
        if member.kind in ("array", "chars"):
            needs_std = True
        if member.kind == "value" and member.cpp in ("Vector", "QAngle"):
            includes.add("<VoltMod/Engine/EngineTypes.hpp>")
    if needs_std:
        includes.add("<cstddef>")
    includes.add("<cstdint>")

    lines = [BANNER, "#pragma once", ""]
    lines += [f"#include {inc}" for inc in sorted(includes)]
    lines += ["", "namespace VoltMod::Schema", "{", ""]

    parent = klass.base or "View"
    lines.append(f"/** Frame-local view over an engine {klass.name}; never store one. */")
    lines.append(f"class {klass.name} : public {parent}")
    lines.append("{")
    lines.append("public:")
    if klass.name == ENTITY_ROOT:
        # An entity is its own notification target, so a write anywhere inside it - including
        # inside a struct it embeds - knows which entity to dirty and at what offset.
        lines += [
            f"    {klass.name}() = default;",
            "",
            f"    explicit {klass.name}(::{ENTITY_ROOT}* entity) noexcept",
            "        : View(entity, entity, 0)",
            "    {",
            "    }",
            "",
            f"    explicit {klass.name}(void* base) noexcept",
            f"        : View(base, static_cast<::{ENTITY_ROOT}*>(base), 0)",
            "    {",
            "    }",
        ]
    else:
        lines.append(f"    using {parent}::{parent};")

    body: list[str] = []
    for member in klass.members:
        body.append("")
        body += member_signature(member)
        if klass.writable:
            body += member_setters(member)
    lines += [f"    {line}" if line else "" for line in body]

    lines += ["};", "", "}  // namespace VoltMod::Schema", ""]
    return "\n".join(lines)


def emit_enums(enums: dict[str, Any]) -> str:
    lines = [BANNER, "#pragma once", "", "#include <cstdint>", "",
             "namespace VoltMod::Schema", "{", ""]
    for name, info in enums.items():
        lines.append(f"/** Schema enum {name}. */")
        lines.append(f"enum class {cpp_identifier(name)} : {enum_underlying(info['size'])}")
        lines.append("{")
        seen: set[int] = set()
        for item in info["items"]:
            # C++ rejects duplicate enumerators; the schema allows aliases.
            if item["value"] in seen:
                lines.append(f"    // alias: {item['name']} = {item['value']}")
                continue
            seen.add(item["value"])
            lines.append(f"    {item['name']} = {item['value']},")
        lines += ["};", ""]
    lines += ["}  // namespace VoltMod::Schema", ""]
    return "\n".join(lines)


def emit_api(classes: dict[str, Klass]) -> str:
    lines = [BANNER, "#pragma once", ""]
    lines.append("#include <VoltMod/Schema/Generated/Enums.hpp>")
    lines.append("#include <VoltMod/Schema/Layout.hpp>")
    lines.append("#include <VoltMod/Schema/Notify.hpp>")
    lines.append("#include <VoltMod/Schema/View.hpp>")
    lines += [
        f"#include <VoltMod/Schema/Generated/{k.name}.hpp>" for k in sorted_classes(classes)
    ]
    lines.append("")
    return "\n".join(lines)


def offset_constant(klass: Klass, member: Member) -> str:
    return f"k{klass.name}_{member.accessor}"


def notify_call(klass: Klass, constant: str) -> list[str]:
    """How a write on this class reaches the engine's dirty tracking."""
    if klass.chain_offset >= 0:
        return [f"    NotifyThroughChain(_base, {klass.name}_kChainOffset, {constant});"]
    # An entity view owns itself at offset 0, so this covers both the entity and the
    # embedded-in-an-entity case with one branch.
    return ["    if (_owner)", f"        NotifyEntity(_owner, _ownerOffset + {constant});"]


def emit_definitions(klass: Klass) -> list[str]:
    """The `Generated.cpp` block for one class."""
    lines = [f"// ---- {klass.name}, {klass.size} bytes " + "-" * max(0, 50 - len(klass.name))]
    if klass.chain_offset >= 0:
        lines.append(
            f"static constexpr int32_t {klass.name}_kChainOffset = {klass.chain_offset};"
        )
    for member in klass.members:
        if member.kind == "skipped":
            continue
        lines.append(
            f"static constexpr int32_t {offset_constant(klass, member)} = {member.offset};"
            f"  // {member.note}"
        )
    lines.append("")

    for member in klass.members:
        if member.kind == "skipped":
            continue
        constant = offset_constant(klass, member)
        name, cls = member.accessor, klass.name

        if member.kind in ("value", "handle", "enum"):
            cpp = cpp_identifier(member.cpp) if member.kind == "enum" else member.cpp
            lines += [
                f"{cpp} {cls}::{name}() const",
                "{",
                "    if (!_base)",
                "        return {};",
                "",
                f"    return *MemberPtr<{cpp}>(_base, {constant});",
                "}",
                "",
            ]
            if klass.writable:
                lines += [f"void {cls}::Set{name}({cpp} value) const", "{"]
                lines += ["    if (!_base)", "        return;", ""]
                lines.append(f"    *MemberPtr<{cpp}>(_base, {constant}) = value;")
                lines += notify_call(klass, constant)
                lines += ["}", ""]

        elif member.kind == "view":
            if member.embedded:
                construct = (
                    f"{member.view}{{MemberPtr<void>(_base, {constant}), _owner, "
                    f"_ownerOffset + {constant}}}"
                )
            else:
                construct = f"{member.view}{{*MemberPtr<void*>(_base, {constant})}}"
            lines += [
                f"{member.view} {cls}::{name}() const",
                "{",
                "    if (!_base)",
                "        return {};",
                "",
                f"    return {construct};",
                "}",
                "",
            ]

        elif member.kind == "chars":
            lines += [
                f"std::string_view {cls}::{name}() const",
                "{",
                "    if (!_base)",
                "        return {};",
                "",
                f"    const char* text = MemberPtr<const char>(_base, {constant});",
                f"    return std::string_view(text, ::strnlen(text, {member.extent} - 1));",
                "}",
                "",
            ]
            if klass.writable:
                lines += [
                    f"void {cls}::Set{name}(std::string_view value) const",
                    "{",
                    "    if (!_base)",
                    "        return;",
                    "",
                    f"    *MemberPtr<CharBuf<{member.extent}>>(_base, {constant}) = value;",
                ]
                lines += notify_call(klass, constant)
                lines += ["}", ""]

        elif member.kind == "array":
            lines += [
                f"{member.cpp} {cls}::{name}(size_t index) const",
                "{",
                f"    if (!_base || index >= {member.extent})",
                "        return {};",
                "",
                f"    return MemberPtr<{member.cpp}>(_base, {constant})[index];",
                "}",
                "",
            ]
            if klass.writable:
                lines += [
                    f"void {cls}::Set{name}(size_t index, {member.cpp} value) const",
                    "{",
                    f"    if (!_base || index >= {member.extent})",
                    "        return;",
                    "",
                    f"    MemberPtr<{member.cpp}>(_base, {constant})[index] = value;",
                ]
                lines += notify_call(
                    klass, f"{constant} + static_cast<int32_t>(index * sizeof({member.cpp}))"
                )
                lines += ["}", ""]

        elif member.kind == "raw":
            lines += [
                f"void* {cls}::{name}() const",
                "{",
                f"    return _base ? MemberPtr<void>(_base, {constant}) : nullptr;",
                "}",
                "",
            ]

    return lines


def forwarder_lines(klass: Klass, member: Member) -> list[str]:
    """The inline forwarders one member contributes to a curated wrapper."""
    view = f"Schema::{klass.name}{{_e}}"
    name = member.accessor
    out: list[str] = []

    if member.kind == "skipped":
        return []
    if member.kind in ("value", "handle", "enum"):
        cpp = f"Schema::{cpp_identifier(member.cpp)}" if member.kind == "enum" else member.cpp
        out.append(f"{cpp} {name}() const {{ return {view}.{name}(); }}")
        if klass.writable:
            out.append(
                f"void Set{name}({cpp} value) const {{ {view}.Set{name}(value); }}"
            )
    elif member.kind == "view":
        out.append(f"Schema::{member.view} {name}() const {{ return {view}.{name}(); }}")
    elif member.kind == "chars":
        out.append(f"std::string_view {name}() const {{ return {view}.{name}(); }}")
        if klass.writable:
            out.append(
                f"void Set{name}(std::string_view value) const {{ {view}.Set{name}(value); }}"
            )
    elif member.kind == "array":
        out.append(
            f"{member.cpp} {name}(size_t index) const {{ return {view}.{name}(index); }}"
        )
        if klass.writable:
            out.append(
                f"void Set{name}(size_t index, {member.cpp} value) const "
                f"{{ {view}.Set{name}(index, value); }}"
            )
    elif member.kind == "raw":
        out.append(f"void* {name}() const {{ return {view}.{name}(); }}")
    return out


def emit_wrapper(wrapper: str, class_names: list[str], classes: dict[str, Klass]) -> str:
    """One `include/VoltMod/Schema/Wrappers/<Wrapper>.inc`.

    Included inside the wrapper's class body, so it is a fragment rather than a header: the
    forwarders read the wrapper's own `_e`, and every schema field reaches plugins without a
    hand-written line here.
    """
    lines = [
        BANNER.rstrip("\n"),
        f"// Schema accessors forwarded onto VoltMod::{wrapper}. Included inside the class body.",
    ]
    for name in class_names:
        klass = classes.get(name)
        if klass is None:
            die(f"manifest wrapper '{wrapper}' names class '{name}', which is not generated")
        emitted = [line for m in klass.members for line in forwarder_lines(klass, m)]
        if not emitted:
            continue
        lines += ["", f"// {klass.name}"] + emitted
    lines.append("")
    return "\n".join(lines)


def emit_class_source(klass: Klass) -> str:
    """One `src/Schema/Generated/<Class>.cpp`."""
    includes = {
        "<VoltMod/Engine/MemoryAccess.hpp>",
        f"<VoltMod/Schema/Generated/{klass.name}.hpp>",
        "<VoltMod/Schema/Layout.hpp>",
        "<VoltMod/Schema/Notify.hpp>",
    }
    for member in klass.members:
        if member.kind == "view":
            includes.add(f"<VoltMod/Schema/Generated/{member.view}.hpp>")
        if member.kind == "chars":
            includes.add("<cstring>")

    lines = [BANNER.rstrip("\n"), ""]
    lines += [f"#include {inc}" for inc in sorted(includes)]
    lines += ["", "namespace VoltMod::Schema", "{", ""]
    lines += emit_definitions(klass)

    fields = [m for m in klass.members if m.kind != "skipped"]
    if fields:
        # `extern` on the definition because a namespace-scope const is internal by default;
        # Layout.cpp names this array so the offsets stay defined once, beside the accessors
        # that use them, rather than being restated in the table.
        lines.append(f"extern const FieldLayout {klass.name}_kFields[{len(fields)}];")
        lines.append(f"const FieldLayout {klass.name}_kFields[{len(fields)}] = {{")
        for member in fields:
            lines.append(
                f'    {{.Name = "{member.schema_name}", '
                f".Offset = {offset_constant(klass, member)}, .Size = {member.size}}},"
            )
        lines += ["};", ""]

    lines += ["}  // namespace VoltMod::Schema", ""]
    return "\n".join(lines)


def emit_layout_source(classes: dict[str, Klass]) -> str:
    """`src/Schema/Generated/Layout.cpp`: the table the load-time verifier walks."""
    ordered = sorted_classes(classes)
    lines = [
        BANNER.rstrip("\n"),
        "",
        "#include <VoltMod/Schema/Layout.hpp>",
        "",
        "namespace VoltMod::Schema",
        "{",
        "",
        "// Defined beside the accessors that share their offsets, in each class's own file.",
    ]
    for klass in ordered:
        count = len([m for m in klass.members if m.kind != "skipped"])
        if count:
            lines.append(f"extern const FieldLayout {klass.name}_kFields[{count}];")
    lines.append("")

    lines.append("static const ClassLayout kClasses[] = {")
    for klass in ordered:
        count = len([m for m in klass.members if m.kind != "skipped"])
        span = f"{{{klass.name}_kFields, {count}}}" if count else "{}"
        lines.append(
            f'    {{.Name = "{klass.name}", .Size = {klass.size}, '
            f".ChainOffset = {klass.chain_offset}, .Fields = {span}}},"
        )
    lines += ["};", ""]

    lines += [
        "std::span<const ClassLayout> GeneratedLayout()",
        "{",
        "    return kClasses;",
        "}",
        "",
        "}  // namespace VoltMod::Schema",
        "",
    ]
    return "\n".join(lines)


def trimmed_dump(dump: dict[str, Any], classes: dict[str, Klass],
                 enums: dict[str, Any]) -> dict[str, Any]:
    """The dump reduced to what the generator read, for committing beside the output."""
    return {
        "format": dump["format"],
        "scopes": dump["scopes"],
        "classes": {name: dump["classes"][name] for name in sorted(classes)},
        "enums": dict(sorted(enums.items())),
    }


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


@app.callback(invoke_without_command=True)
def schemagen(
    dump_path: Annotated[
        str, typer.Option("--dump", help="Schema dump written by the schema_dump command.")
    ],
    root: Annotated[str, typer.Option("--root", help="Repository root to write into.")] = ".",
) -> None:
    """Regenerate the schema accessor layer from a dump."""
    repo = Path(root).resolve()
    manifest_path = repo / SCHEMA_DIR / "manifest.json"
    if not manifest_path.is_file():
        die(f"no manifest at {manifest_path}")

    source = Path(dump_path)
    if not source.is_file():
        die(f"no dump at {source}")

    dump = json.loads(source.read_text(encoding="utf-8"))
    if dump.get("format") != 1:
        die(f"dump format {dump.get('format')} is not supported; expected 1")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    classes = build_classes(dump, manifest)
    enums = collect_enums(dump, classes)

    headers = repo / HEADER_DIR
    generated = repo / GENERATED_DIR
    # Everything under Generated/ is rewritten wholesale, so a class dropped from the manifest
    # leaves no orphan header behind.
    for stale in sorted(generated.rglob("*")):
        if stale.is_file():
            stale.unlink()

    for klass in sorted_classes(classes):
        write(generated / f"{klass.name}.hpp", emit_header(klass, classes))
    write(generated / "Enums.hpp", emit_enums(enums))
    write(headers / "Api.hpp", emit_api(classes))
    for wrapper, names in manifest.get("wrappers", {}).items():
        write(generated / "Wrappers" / f"{wrapper}.inc", emit_wrapper(wrapper, names, classes))
    sources = repo / GENERATED_SRC_DIR
    for stale in sorted(sources.glob("*.cpp")):
        stale.unlink()
    for klass in sorted_classes(classes):
        write(sources / f"{klass.name}.cpp", emit_class_source(klass))
    write(sources / "Layout.cpp", emit_layout_source(classes))
    write(
        repo / SCHEMA_DIR / "server.json",
        json.dumps(trimmed_dump(dump, classes, enums), indent=2) + "\n",
    )

    written_files = sorted(headers.rglob("*.hpp")) + sorted(generated.rglob("*.inc"))
    written_files += sorted(sources.glob("*.cpp"))
    run_tool("clang-format", "-i", *(str(f) for f in written_files))

    skipped = sum(1 for k in classes.values() for m in k.members if m.kind == "skipped")
    fields = sum(1 for k in classes.values() for m in k.members if m.kind != "skipped")
    print(f"schemagen: {len(classes)} classes, {len(enums)} enums, {fields} fields"
          + (f", {skipped} skipped" if skipped else ""))
