#include "Support/FakePanel.hpp"
#include "Ui/Fixtures/Lab.hpp"

#include <VoltMod/Ui/Writers.hpp>
#include <doctest/doctest.h>
#include <array>
#include <cstddef>
#include <ostream>
#include <string>
#include <string_view>
#include <vector>

using VoltMod::ClassChoice;
using VoltMod::ClassFlag;
using VoltMod::TextVar;
using VoltModTests::FakePanel;

/* Lab.hpp is written by `voltmod panorama bind` and regenerated by cli/tests/test_bind.py, so
   this is the emitted C++ being compiled and run. It emits constants only; assembling them into
   writers is the plugin's job, and this is what that looks like. */

namespace
{

struct LabCard
{
    TextVar Title;
    TextVar Subtitle;
    TextVar Value;
    ClassChoice Icon;
    ClassChoice Bar;
    ClassChoice Accent;
    ClassFlag Hidden;
};

constexpr LabCard MakeCard(std::string_view panel, std::string_view icon, std::string_view bar,
                           std::string_view accent, std::string_view title, std::string_view subtitle,
                           std::string_view value)
{
    return {
        .Title = {LabUi::RootId, title},
        .Subtitle = {LabUi::RootId, subtitle},
        .Value = {LabUi::RootId, value},
        .Icon = {icon, LabUi::IconClasses},
        .Bar = {bar, LabUi::StepClasses},
        .Accent = {accent, LabUi::AccentClasses},
        .Hidden = {panel, "Hidden"},
    };
}

constexpr std::array<LabCard, 2> Card{
    MakeCard(LabUi::Card0, LabUi::Card0Icon, LabUi::Card0Bar, LabUi::Card0Accent, LabUi::Card0TitleVar,
             LabUi::Card0SubtitleVar, LabUi::Card0ValueVar),
    MakeCard(LabUi::Card1, LabUi::Card1Icon, LabUi::Card1Bar, LabUi::Card1Accent, LabUi::Card1TitleVar,
             LabUi::Card1SubtitleVar, LabUi::Card1ValueVar),
};

constexpr struct
{
    TextVar Title{LabUi::RootId, LabUi::ToastTitleVar};
    TextVar Description{LabUi::RootId, LabUi::ToastDescriptionVar};
    ClassChoice Accent{LabUi::ToastAccent, LabUi::AccentClasses};
    ClassFlag Show{LabUi::Toast, "Show"};
} Toast;

constexpr ClassFlag Hidden{LabUi::RootId, "Hidden"};

}  // namespace

static_assert(LabUi::Layout == "lab");
static_assert(Card.size() == 2);
static_assert(Card[1].Bar.Count() == 5);
static_assert(LabUi::Icon::Awp == static_cast<LabUi::Icon>(1));

TEST_CASE("A screen writes through every widget built from its constants")
{
    FakePanel panel;

    Hidden.Write(panel, 2, false);
    Card[0].Hidden.Write(panel, 2, true);
    Card[0].Title.Write(panel, 2, "AK-47");
    Card[0].Subtitle.Write(panel, 2, "Rifle");
    Card[0].Value.Write(panel, 2, "12");
    Card[0].Accent.Write(panel, 2, static_cast<int>(LabUi::Accent::Good));
    Card[0].Icon.Write(panel, 2, Card[0].Icon.Find("awp"));
    Card[0].Bar.Write(panel, 2, 4);
    Card[1].Title.Write(panel, 2, "AWP");
    Toast.Show.Write(panel, 2, true);
    Toast.Title.Write(panel, 2, "Round over");
    Toast.Description.Write(panel, 2, "Terrorists win");
    Toast.Accent.Write(panel, 2, static_cast<int>(LabUi::Accent::Bad));

    const std::vector<std::string> enabled = panel.Enabled();
    CHECK(enabled
          == std::vector<std::string>{"lab_card0.Hidden", "lab_card0_accent.Accent--good",
                                      "lab_card0_icon.Icon--awp", "lab_card0_bar.Step--4",
                                      "lab_toast.Show", "lab_toast_accent.Accent--bad"});
}

TEST_CASE("A text widget names the layout root, not the panel")
{
    FakePanel panel;

    Card[1].Value.Write(panel, 0, "1");

    REQUIRE(panel.Texts.size() == 1);
    const auto& [slot, id, var, value] = panel.Texts[0];
    CHECK(id == LabUi::RootId);
    CHECK(var == "card1_value");
    CHECK(slot == 0);
    CHECK(value == "1");
}

TEST_CASE("A family clears the classes it is not on")
{
    FakePanel panel;

    Card[0].Bar.Write(panel, 0, ClassChoice::None);

    CHECK(static_cast<int>(panel.Classes.size()) == Card[0].Bar.Count());
    CHECK(panel.Enabled().empty());
}

TEST_CASE("A family finds its index by variant name")
{
    CHECK(Toast.Accent.Find("bad") == static_cast<int>(LabUi::Accent::Bad));
    CHECK(Toast.Accent.Find("Accent--good") == 0);
    CHECK(Card[0].Icon.Find(LabUi::IconNames[1]) == 1);
    CHECK(Card[0].Bar.Find("3") == 3);
    CHECK(Card[0].Icon.Find("famas") == ClassChoice::None);
}
