#include "Ui/Fixtures/Lab.hpp"

#include <doctest/doctest.h>
#include <string_view>

/* Lab.hpp is written by `voltmod panorama render` and regenerated by cli/tests/test_panorama_layout.py,
   so these are the emitted constants being compiled against the ids a plugin writes. */

static_assert(LabLayout::Name == "lab");
static_assert(LabLayout::Close == "lab_close");
static_assert(LabLayout::CloseVar == "close");

static_assert(LabLayout::Rows.size() == 2);
static_assert(LabLayout::Rows[1].Id == "lab_row1");
static_assert(LabLayout::Rows[1].Button == "lab_row1_button");
static_assert(LabLayout::Rows[1].Decrease == "lab_row1_decrease");
static_assert(LabLayout::Rows[1].Increase == "lab_row1_increase");
static_assert(LabLayout::Rows[0].LabelVar == "row0_label");

static_assert(LabLayout::IconSetNames.size() == 2);
static_assert(LabLayout::IconSetNames[1] == "awp");

TEST_CASE("Every repeated row names its own elements and variables")
{
    for (std::size_t index = 0; index < LabLayout::Rows.size(); ++index)
    {
        const LabLayout::Row& row = LabLayout::Rows[index];
        CAPTURE(index);
        CHECK(row.Button.starts_with(row.Id));
        CHECK(row.Decrease.starts_with(row.Id));
        CHECK(row.Increase.starts_with(row.Id));
        CHECK(row.LabelVar.ends_with("_label"));
    }
}
