#include "Ui/Fixtures/Lab.hpp"

#include <doctest/doctest.h>
#include <string_view>

/* Lab.hpp is written by `voltmod panorama render` and regenerated by cli/tests/test_panorama_layout.py,
   so these are the emitted constants being compiled against the ids a plugin writes. */

static_assert(LabUi::Layout == "lab");
static_assert(LabUi::RootId == LabUi::Layout);
static_assert(LabUi::Close == "lab_close");
static_assert(LabUi::CloseVar == "close");

static_assert(LabUi::Rows.size() == 2);
static_assert(LabUi::Rows[1].Id == "lab_row1");
static_assert(LabUi::Rows[1].Button == "lab_row1_button");
static_assert(LabUi::Rows[1].Decrease == "lab_row1_decrease");
static_assert(LabUi::Rows[1].Increase == "lab_row1_increase");
static_assert(LabUi::Rows[0].LabelVar == "row0_label");

static_assert(LabUi::IconSetClasses.size() == 2);
static_assert(LabUi::IconSetClasses[1] == "icon-set--awp");
static_assert(LabUi::IconSetNames[1] == "awp");

TEST_CASE("Every repeated row names its own elements and variables")
{
    for (std::size_t index = 0; index < LabUi::Rows.size(); ++index)
    {
        const LabUi::Row& row = LabUi::Rows[index];
        CAPTURE(index);
        CHECK(row.Button.starts_with(row.Id));
        CHECK(row.Decrease.starts_with(row.Id));
        CHECK(row.Increase.starts_with(row.Id));
        CHECK(row.LabelVar.ends_with("_label"));
    }
}
