#include "Support/FakePanel.hpp"
#include "Ui/Fixtures/Lab.hpp"

#include <VoltMod/Ui/Writers.hpp>
#include <array>
#include <cstddef>
#include <doctest/doctest.h>
#include <ostream>
#include <string>
#include <string_view>
#include <vector>

using VoltMod::ClassChoice;
using VoltMod::ClassFlag;
using VoltMod::PanelWriter;
using VoltMod::TextVar;
using VoltModTests::FakePanel;

/* Lab.hpp is written by `voltmod panorama render` and regenerated by cli/tests/test_bind.py, so
   this is the emitted C++ being compiled and run. It emits constants and the repeated `Cards`
   block; turning those into writers is the plugin's job, and this is what that looks like. */

namespace
{

struct CardWriters
{
    TextVar Title;
    TextVar Subtitle;
    TextVar Value;
    ClassChoice Icon;
    ClassChoice Bar;
    ClassChoice Accent;
    ClassFlag Hidden;
};

constexpr CardWriters MakeCard(const LabUi::Card& card)
{
    return {
        .Title = {LabUi::RootId, card.TitleVar},
        .Subtitle = {LabUi::RootId, card.SubtitleVar},
        .Value = {LabUi::RootId, card.ValueVar},
        .Icon = {card.Icon, LabUi::IconClasses},
        .Bar = {card.Bar, LabUi::StepClasses},
        .Accent = {card.Accent, LabUi::AccentClasses},
        .Hidden = {card.Id, "Hidden"},
    };
}

constexpr auto Cards = VoltMod::MakeWriters(LabUi::Cards, MakeCard);

constexpr struct
{
    TextVar Title{LabUi::RootId, LabUi::ToastTitleVar};
    TextVar Description{LabUi::RootId, LabUi::ToastDescriptionVar};
    ClassChoice Accent{LabUi::ToastAccent, LabUi::AccentClasses};
    ClassFlag Show{LabUi::Toast, "Show"};
} Toast;

constexpr ClassFlag Hidden{LabUi::RootId, "Hidden"};

}  // namespace

static_assert(LabUi::Layout == "lab");
static_assert(LabUi::Cards.size() == 2);
static_assert(Cards.size() == LabUi::Cards.size());
static_assert(Cards[1].Hidden.Id == "lab_card1");
static_assert(Cards[1].Bar.Count() == 5);
static_assert(LabUi::Icon::Awp == static_cast<LabUi::Icon>(1));

TEST_CASE("A screen writes through every writer built from its constants")
{
    FakePanel panel;
    const PanelWriter<FakePanel> w{panel, 2};

    w.Set(Hidden, false);
    w.Set(Cards[0].Hidden, true);
    w.Set(Cards[0].Title, "AK-47");
    w.Set(Cards[0].Subtitle, "Rifle");
    w.Set(Cards[0].Value, "12");
    w.Set(Cards[0].Accent, static_cast<int>(LabUi::Accent::Good));
    w.Set(Cards[0].Icon, Cards[0].Icon.Find("awp"));
    w.Set(Cards[0].Bar, 4);
    w.Set(Cards[1].Title, "AWP");
    w.Set(Toast.Show, true);
    w.Set(Toast.Title, "Round over");
    w.Set(Toast.Description, "Terrorists win");
    w.Set(Toast.Accent, static_cast<int>(LabUi::Accent::Bad));

    const std::vector<std::string> enabled = panel.Enabled();
    CHECK(enabled == std::vector<std::string>{"lab_card0.Hidden", "lab_card0_accent.Accent--good",
                                              "lab_card0_icon.Icon--awp", "lab_card0_bar.Step--4", "lab_toast.Show",
                                              "lab_toast_accent.Accent--bad"});
}

TEST_CASE("A text writer names the layout root, not the panel")
{
    FakePanel panel;

    Cards[1].Value.Write(panel, 0, "1");

    REQUIRE(panel.Texts.size() == 1);
    const auto& [slot, id, var, value] = panel.Texts[0];
    CHECK(id == LabUi::RootId);
    CHECK(var == "card1_value");
    CHECK(slot == 0);
    CHECK(value == "1");
}

// ClassChoice's own write and lookup rules are covered in WritersTests; what is checked here is
// that the generated enums and name tables line up with the class families they were emitted from.
TEST_CASE("A generated family's enumerators index its own classes")
{
    CHECK(Toast.Accent.Find("bad") == static_cast<int>(LabUi::Accent::Bad));
    CHECK(Cards[0].Icon.Find(LabUi::IconNames[1]) == static_cast<int>(LabUi::Icon::Awp));
    CHECK(Cards[0].Bar.Find("3") == 3);
    CHECK(Cards[0].Icon.Find("famas") == ClassChoice::None);
}
