"""The resolved shape of one generated class, and the naming rules that produce it."""

from dataclasses import dataclass, field

# The entity root: a class reaching this by inheritance replicates through the entity itself.
ENTITY_ROOT = "CEntityInstance"

BANNER = "// Generated by `voltmod schemagen`. Do not edit.\n"

# Hungarian prefixes stripped from a field name to get its accessor. Only these, and only when
# an uppercase letter follows, so `m_lifeState` keeps its name instead of becoming `State`.
PREFIXES = {
    "a", "ang", "arr", "b", "cl", "clr", "d", "e", "f", "fl", "fn", "h", "i", "isz", "m",
    "n", "nv", "p", "pp", "psz", "pv", "q", "s", "str", "sz", "t", "u", "ub", "ui", "un",
    "v", "vec", "w", "x", "y", "z",
}


@dataclass
class Member:
    """One manifest field resolved against the dump."""

    schema_name: str
    accessor: str
    offset: int
    size: int
    kind: str  # value | enum | view | handle | chars | array | raw | skipped
    cpp: str = ""  # the C++ type for value/enum/handle/array element
    view: str = ""  # the schema class for a view
    embedded: bool = False  # a view held by value rather than behind a pointer
    extent: int = 0
    note: str = ""  # schema type spelling, for the offset comment
    skip_reason: str = ""

    @property
    def generated(self) -> bool:
        """Whether this member reaches the generated output at all."""
        return self.kind != "skipped"


@dataclass
class Klass:
    """One generated class."""

    name: str
    size: int
    chain_offset: int
    base: str | None
    entity_rooted: bool = False
    embeds_in_entity: bool = False
    members: list[Member] = field(default_factory=list)

    @property
    def writable(self) -> bool:
        """Whether a write on this class has a route to the engine's dirty tracking."""
        return self.entity_rooted or self.chain_offset >= 0 or self.embeds_in_entity

    @property
    def fields(self) -> list[Member]:
        """The members that carry a baked offset, in declaration order."""
        return [m for m in self.members if m.generated]


def accessor_name(schema_name: str) -> str:
    """`m_flVelocityModifier` -> `VelocityModifier`. Raises when nothing usable is left."""
    body = schema_name.removeprefix("m_")
    if not body:
        raise ValueError(f"{schema_name}: no name left after m_")

    for size in (3, 2, 1):
        prefix, rest = body[:size], body[size:]
        if prefix in PREFIXES and rest[:1].isupper() and len(rest) >= 3:
            return rest

    if body[0].islower():
        return body[0].upper() + body[1:]
    return body


def parse_entry(entry: str) -> tuple[str, str | None, str | None]:
    """Split a manifest field entry into (schema name, accessor override, C++ type override)."""
    name, _, cpp = entry.partition(":")
    name, _, rename = name.partition(">")
    return name, rename or None, cpp or None


def cpp_identifier(name: str) -> str:
    """A schema name usable as a C++ identifier (`CFuncMover::Move_t` is nested in schema)."""
    return name.replace("::", "_")


def enum_underlying(size: int) -> str:
    return {1: "int8_t", 2: "int16_t", 4: "int32_t", 8: "int64_t"}.get(size, "int32_t")


def sorted_classes(classes: dict[str, Klass]) -> list[Klass]:
    return [classes[name] for name in sorted(classes)]


def offset_constant(klass: Klass, member: Member) -> str:
    return f"k{klass.name}_{member.accessor}"
