// Generated by `voltmod framework eventgen` from the game's .gameevents files. Do not edit.

#include <igameevents.h>

#include <VoltMod/Events/EventTypes.hpp>
#include <gametrace.h>
#include <playerslot.h>
#include <utility>

namespace VoltMod
{

static_assert(std::to_underlying(HitGroup::Invalid) == HITGROUP_INVALID);
static_assert(std::to_underlying(HitGroup::Generic) == HITGROUP_GENERIC);
static_assert(std::to_underlying(HitGroup::Head) == HITGROUP_HEAD);
static_assert(std::to_underlying(HitGroup::Chest) == HITGROUP_CHEST);
static_assert(std::to_underlying(HitGroup::Stomach) == HITGROUP_STOMACH);
static_assert(std::to_underlying(HitGroup::LeftArm) == HITGROUP_LEFTARM);
static_assert(std::to_underlying(HitGroup::RightArm) == HITGROUP_RIGHTARM);
static_assert(std::to_underlying(HitGroup::LeftLeg) == HITGROUP_LEFTLEG);
static_assert(std::to_underlying(HitGroup::RightLeg) == HITGROUP_RIGHTLEG);
static_assert(std::to_underlying(HitGroup::Neck) == HITGROUP_NECK);

AchievementEarned AchievementEarned::From(IGameEvent& e)
{
    return {
        .PlayerSlot = e.GetPlayerSlot("player").Get(),
        .Achievement = e.GetInt("achievement"),
    };
}

AchievementEarnedLocal AchievementEarnedLocal::From(IGameEvent& e)
{
    return {
        .Achievement = e.GetInt("achievement"),
        .Splitscreenplayer = e.GetInt("splitscreenplayer"),
    };
}

AchievementEvent AchievementEvent::From(IGameEvent& e)
{
    return {
        .AchievementName = e.GetString("achievement_name", ""),
        .CurVal = e.GetInt("cur_val"),
        .MaxVal = e.GetInt("max_val"),
    };
}

AchievementInfoLoaded AchievementInfoLoaded::From(IGameEvent&)
{
    return {};
}

AchievementWriteFailed AchievementWriteFailed::From(IGameEvent&)
{
    return {};
}

AddBulletHitMarker AddBulletHitMarker::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Bone = e.GetInt("bone"),
        .PosX = e.GetInt("pos_x"),
        .PosY = e.GetInt("pos_y"),
        .PosZ = e.GetInt("pos_z"),
        .AngX = e.GetInt("ang_x"),
        .AngY = e.GetInt("ang_y"),
        .AngZ = e.GetInt("ang_z"),
        .StartX = e.GetInt("start_x"),
        .StartY = e.GetInt("start_y"),
        .StartZ = e.GetInt("start_z"),
        .Hit = e.GetBool("hit"),
    };
}

AddPlayerSonarIcon AddPlayerSonarIcon::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .PosX = e.GetFloat("pos_x"),
        .PosY = e.GetFloat("pos_y"),
        .PosZ = e.GetFloat("pos_z"),
    };
}

AmmoPickup AmmoPickup::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Item = e.GetString("item", ""),
        .Index = e.GetInt("index"),
    };
}

AmmoRefill AmmoRefill::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Success = e.GetBool("success"),
    };
}

AnnouncePhaseEnd AnnouncePhaseEnd::From(IGameEvent&)
{
    return {};
}

BeginNewMatch BeginNewMatch::From(IGameEvent&)
{
    return {};
}

BombAbortdefuse BombAbortdefuse::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

BombAbortplant BombAbortplant::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Site = e.GetInt("site"),
    };
}

BombBeep BombBeep::From(IGameEvent& e)
{
    return {
        .Entindex = e.GetInt("entindex"),
    };
}

BombBegindefuse BombBegindefuse::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Haskit = e.GetBool("haskit"),
    };
}

BombBeginplant BombBeginplant::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Site = e.GetInt("site"),
    };
}

BombDefused BombDefused::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Site = e.GetInt("site"),
        .C4 = e.GetInt("c4"),
    };
}

BombDropped BombDropped::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Entindex = e.GetInt("entindex"),
    };
}

BombExploded BombExploded::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Site = e.GetInt("site"),
        .C4 = e.GetInt("c4"),
    };
}

BombPickup BombPickup::From(IGameEvent&)
{
    return {};
}

BombPlanted BombPlanted::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Site = e.GetInt("site"),
        .C4 = e.GetInt("c4"),
    };
}

BonusUpdated BonusUpdated::From(IGameEvent& e)
{
    return {
        .Numadvanced = e.GetInt("numadvanced"),
        .Numbronze = e.GetInt("numbronze"),
        .Numsilver = e.GetInt("numsilver"),
        .Numgold = e.GetInt("numgold"),
    };
}

BotTakeover BotTakeover::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .BotidSlot = e.GetPlayerSlot("botid").Get(),
        .P = e.GetFloat("p"),
        .Y = e.GetFloat("y"),
        .R = e.GetFloat("r"),
    };
}

BreakBreakable BreakBreakable::From(IGameEvent& e)
{
    return {
        .Entindex = e.GetInt("entindex"),
        .Material = e.GetInt("material"),
    };
}

BreakProp BreakProp::From(IGameEvent& e)
{
    return {
        .Entindex = e.GetInt("entindex"),
    };
}

BrokenBreakable BrokenBreakable::From(IGameEvent& e)
{
    return {
        .Entindex = e.GetInt("entindex"),
        .Material = e.GetInt("material"),
    };
}

BulletDamage BulletDamage::From(IGameEvent& e)
{
    return {
        .VictimSlot = e.GetPlayerSlot("victim").Get(),
        .AttackerSlot = e.GetPlayerSlot("attacker").Get(),
        .Distance = e.GetFloat("distance"),
        .DamageDirX = e.GetFloat("damage_dir_x"),
        .DamageDirY = e.GetFloat("damage_dir_y"),
        .DamageDirZ = e.GetFloat("damage_dir_z"),
        .NumPenetrations = e.GetInt("num_penetrations"),
        .NoScope = e.GetBool("no_scope"),
        .InAir = e.GetBool("in_air"),
        .ShootAngX = e.GetFloat("shoot_ang_x"),
        .ShootAngY = e.GetFloat("shoot_ang_y"),
        .ShootAngZ = e.GetFloat("shoot_ang_z"),
        .AimPunchX = e.GetFloat("aim_punch_x"),
        .AimPunchY = e.GetFloat("aim_punch_y"),
        .AimPunchZ = e.GetFloat("aim_punch_z"),
        .AttackTickCount = e.GetInt("attack_tick_count"),
        .AttackTickFrac = e.GetFloat("attack_tick_frac"),
        .RenderTickCount = e.GetInt("render_tick_count"),
        .RenderTickFrac = e.GetFloat("render_tick_frac"),
        .InaccuracyTotal = e.GetFloat("inaccuracy_total"),
        .InaccuracyMove = e.GetFloat("inaccuracy_move"),
        .InaccuracyAir = e.GetFloat("inaccuracy_air"),
        .RecoilIndex = e.GetFloat("recoil_index"),
        .Type = e.GetInt("type"),
    };
}

BuymenuClose BuymenuClose::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

BuymenuOpen BuymenuOpen::From(IGameEvent&)
{
    return {};
}

BuytimeEnded BuytimeEnded::From(IGameEvent&)
{
    return {};
}

CartUpdated CartUpdated::From(IGameEvent&)
{
    return {};
}

ChoppersIncomingWarning ChoppersIncomingWarning::From(IGameEvent& e)
{
    return {
        .Global = e.GetBool("global"),
    };
}

ClientDisconnect ClientDisconnect::From(IGameEvent&)
{
    return {};
}

ClientLoadoutChanged ClientLoadoutChanged::From(IGameEvent&)
{
    return {};
}

ClientsideLessonClosed ClientsideLessonClosed::From(IGameEvent& e)
{
    return {
        .LessonName = e.GetString("lesson_name", ""),
    };
}

ClientsideReloadCustomEcon ClientsideReloadCustomEcon::From(IGameEvent& e)
{
    return {
        .Steamid = e.GetString("steamid", ""),
    };
}

CsGameDisconnected CsGameDisconnected::From(IGameEvent&)
{
    return {};
}

CsIntermission CsIntermission::From(IGameEvent&)
{
    return {};
}

CsMatchEndRestart CsMatchEndRestart::From(IGameEvent&)
{
    return {};
}

CsPreRestart CsPreRestart::From(IGameEvent&)
{
    return {};
}

CsPrevNextSpectator CsPrevNextSpectator::From(IGameEvent& e)
{
    return {
        .Next = e.GetBool("next"),
    };
}

CsRoundFinalBeep CsRoundFinalBeep::From(IGameEvent&)
{
    return {};
}

CsRoundStartBeep CsRoundStartBeep::From(IGameEvent&)
{
    return {};
}

CsWinPanelMatch CsWinPanelMatch::From(IGameEvent&)
{
    return {};
}

CsWinPanelRound CsWinPanelRound::From(IGameEvent& e)
{
    return {
        .ShowTimerDefend = e.GetBool("show_timer_defend"),
        .ShowTimerAttack = e.GetBool("show_timer_attack"),
        .TimerTime = e.GetInt("timer_time"),
        .FinalEvent = e.GetInt("final_event"),
        .FunfactToken = e.GetString("funfact_token", ""),
        .FunfactPlayerSlot = e.GetPlayerSlot("funfact_player").Get(),
        .FunfactData1 = e.GetInt("funfact_data1"),
        .FunfactData2 = e.GetInt("funfact_data2"),
        .FunfactData3 = e.GetInt("funfact_data3"),
    };
}

DecoyDetonate DecoyDetonate::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

DecoyFiring DecoyFiring::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

DecoyStarted DecoyStarted::From(IGameEvent& e)
{
    return {
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

DefuserDropped DefuserDropped::From(IGameEvent& e)
{
    return {
        .Entityid = e.GetInt("entityid"),
    };
}

DefuserPickup DefuserPickup::From(IGameEvent& e)
{
    return {
        .Entityid = e.GetInt("entityid"),
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

DemoSkip DemoSkip::From(IGameEvent& e)
{
    return {
        .PlaybackTick = e.GetInt("playback_tick"),
        .SkiptoTick = e.GetInt("skipto_tick"),
    };
}

DemoStart DemoStart::From(IGameEvent&)
{
    return {};
}

DemoStop DemoStop::From(IGameEvent&)
{
    return {};
}

DifficultyChanged DifficultyChanged::From(IGameEvent& e)
{
    return {
        .NewDifficulty = e.GetInt("newDifficulty"),
        .OldDifficulty = e.GetInt("oldDifficulty"),
        .StrDifficulty = e.GetString("strDifficulty", ""),
    };
}

DmBonusWeaponStart DmBonusWeaponStart::From(IGameEvent& e)
{
    return {
        .Time = e.GetInt("time"),
        .Pos = e.GetInt("Pos"),
    };
}

DoorBreak DoorBreak::From(IGameEvent& e)
{
    return {
        .Entindex = e.GetInt("entindex"),
        .Dmgstate = e.GetInt("dmgstate"),
    };
}

DoorClose DoorClose::From(IGameEvent& e)
{
    return {
        .Checkpoint = e.GetBool("checkpoint"),
    };
}

DoorClosed DoorClosed::From(IGameEvent& e)
{
    return {
        .Entindex = e.GetInt("entindex"),
    };
}

DoorMoving DoorMoving::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Entindex = e.GetInt("entindex"),
    };
}

DoorOpen DoorOpen::From(IGameEvent& e)
{
    return {
        .Entindex = e.GetInt("entindex"),
    };
}

DroneAboveRoof DroneAboveRoof::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Cargo = e.GetInt("cargo"),
    };
}

DroneCargoDetached DroneCargoDetached::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Cargo = e.GetInt("cargo"),
        .Delivered = e.GetBool("delivered"),
    };
}

DroneDispatched DroneDispatched::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Priority = e.GetInt("priority"),
    };
}

DronegunAttack DronegunAttack::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

DropRateModified DropRateModified::From(IGameEvent&)
{
    return {};
}

DynamicShadowLightChanged DynamicShadowLightChanged::From(IGameEvent&)
{
    return {};
}

DzItemInteraction DzItemInteraction::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Subject = e.GetInt("subject"),
        .Type = e.GetString("type", ""),
    };
}

EnableRestartVoting EnableRestartVoting::From(IGameEvent& e)
{
    return {
        .Enable = e.GetBool("enable"),
    };
}

EndmatchCmmStartRevealItems EndmatchCmmStartRevealItems::From(IGameEvent&)
{
    return {};
}

EndmatchMapvoteSelectingMap EndmatchMapvoteSelectingMap::From(IGameEvent& e)
{
    return {
        .Count = e.GetInt("count"),
        .Slot1 = e.GetInt("slot1"),
        .Slot2 = e.GetInt("slot2"),
        .Slot3 = e.GetInt("slot3"),
        .Slot4 = e.GetInt("slot4"),
        .Slot5 = e.GetInt("slot5"),
        .Slot6 = e.GetInt("slot6"),
        .Slot7 = e.GetInt("slot7"),
        .Slot8 = e.GetInt("slot8"),
        .Slot9 = e.GetInt("slot9"),
        .Slot10 = e.GetInt("slot10"),
    };
}

EnterBombzone EnterBombzone::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Hasbomb = e.GetBool("hasbomb"),
        .Isplanted = e.GetBool("isplanted"),
    };
}

EnterBuyzone EnterBuyzone::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Canbuy = e.GetBool("canbuy"),
    };
}

EnterRescueZone EnterRescueZone::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

EntityKilled EntityKilled::From(IGameEvent& e)
{
    return {
        .EntindexKilled = e.GetInt("entindex_killed"),
        .EntindexAttacker = e.GetInt("entindex_attacker"),
        .EntindexInflictor = e.GetInt("entindex_inflictor"),
        .Damagebits = e.GetInt("damagebits"),
    };
}

EntityVisible EntityVisible::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Subject = e.GetInt("subject"),
        .Classname = e.GetString("classname", ""),
        .Entityname = e.GetString("entityname", ""),
    };
}

EventTicketModified EventTicketModified::From(IGameEvent&)
{
    return {};
}

ExitBombzone ExitBombzone::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Hasbomb = e.GetBool("hasbomb"),
        .Isplanted = e.GetBool("isplanted"),
    };
}

ExitBuyzone ExitBuyzone::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Canbuy = e.GetBool("canbuy"),
    };
}

ExitRescueZone ExitRescueZone::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

FinaleStart FinaleStart::From(IGameEvent& e)
{
    return {
        .Rushes = e.GetInt("rushes"),
    };
}

FirstbombsIncomingWarning FirstbombsIncomingWarning::From(IGameEvent& e)
{
    return {
        .Global = e.GetBool("global"),
    };
}

FlareIgniteNpc FlareIgniteNpc::From(IGameEvent& e)
{
    return {
        .Entindex = e.GetInt("entindex"),
    };
}

FlashbangDetonate FlashbangDetonate::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

GameEnd GameEnd::From(IGameEvent& e)
{
    return {
        .Winner = e.GetInt("winner"),
    };
}

GameInit GameInit::From(IGameEvent&)
{
    return {};
}

GameMessage GameMessage::From(IGameEvent& e)
{
    return {
        .Target = e.GetInt("target"),
        .Text = e.GetString("text", ""),
    };
}

GameNewmap GameNewmap::From(IGameEvent& e)
{
    return {
        .Mapname = e.GetString("mapname", ""),
    };
}

GamePhaseChanged GamePhaseChanged::From(IGameEvent& e)
{
    return {
        .NewPhase = e.GetInt("new_phase"),
    };
}

GameStart GameStart::From(IGameEvent& e)
{
    return {
        .Roundslimit = e.GetInt("roundslimit"),
        .Timelimit = e.GetInt("timelimit"),
        .Fraglimit = e.GetInt("fraglimit"),
        .Objective = e.GetString("objective", ""),
    };
}

GameinstructorDraw GameinstructorDraw::From(IGameEvent&)
{
    return {};
}

GameinstructorNodraw GameinstructorNodraw::From(IGameEvent&)
{
    return {};
}

GameuiHidden GameuiHidden::From(IGameEvent&)
{
    return {};
}

GcConnected GcConnected::From(IGameEvent&)
{
    return {};
}

GgKilledEnemy GgKilledEnemy::From(IGameEvent& e)
{
    return {
        .VictimidSlot = e.GetPlayerSlot("victimid").Get(),
        .AttackeridSlot = e.GetPlayerSlot("attackerid").Get(),
        .Dominated = e.GetInt("dominated"),
        .Revenge = e.GetInt("revenge"),
        .Bonus = e.GetBool("bonus"),
    };
}

GrenadeBounce GrenadeBounce::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

GrenadeThrown GrenadeThrown::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Weapon = e.GetString("weapon", ""),
    };
}

GuardianWaveRestart GuardianWaveRestart::From(IGameEvent&)
{
    return {};
}

HegrenadeDetonate HegrenadeDetonate::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

HelicopterGrenadePuntMiss HelicopterGrenadePuntMiss::From(IGameEvent&)
{
    return {};
}

HideDeathpanel HideDeathpanel::From(IGameEvent&)
{
    return {};
}

HltvCameraman HltvCameraman::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

HltvChangedMode HltvChangedMode::From(IGameEvent& e)
{
    return {
        .Oldmode = e.GetInt("oldmode"),
        .Newmode = e.GetInt("newmode"),
        .ObsTarget = e.GetInt("obs_target"),
    };
}

HltvChase HltvChase::From(IGameEvent& e)
{
    return {
        .Target1Slot = e.GetPlayerSlot("target1").Get(),
        .Target2Slot = e.GetPlayerSlot("target2").Get(),
        .Distance = e.GetInt("distance"),
        .Theta = e.GetInt("theta"),
        .Phi = e.GetInt("phi"),
        .Inertia = e.GetInt("inertia"),
        .Ineye = e.GetInt("ineye"),
    };
}

HltvChat HltvChat::From(IGameEvent& e)
{
    return {
        .Text = e.GetString("text", ""),
        .SteamID = e.GetUint64("steamID"),
    };
}

HltvFixed HltvFixed::From(IGameEvent& e)
{
    return {
        .Posx = e.GetInt("posx"),
        .Posy = e.GetInt("posy"),
        .Posz = e.GetInt("posz"),
        .Theta = e.GetInt("theta"),
        .Phi = e.GetInt("phi"),
        .Offset = e.GetInt("offset"),
        .Fov = e.GetFloat("fov"),
        .TargetSlot = e.GetPlayerSlot("target").Get(),
    };
}

HltvMessage HltvMessage::From(IGameEvent& e)
{
    return {
        .Text = e.GetString("text", ""),
    };
}

HltvRankCamera HltvRankCamera::From(IGameEvent& e)
{
    return {
        .Index = e.GetInt("index"),
        .Rank = e.GetFloat("rank"),
        .TargetSlot = e.GetPlayerSlot("target").Get(),
    };
}

HltvRankEntity HltvRankEntity::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Rank = e.GetFloat("rank"),
        .TargetSlot = e.GetPlayerSlot("target").Get(),
    };
}

HltvReplay HltvReplay::From(IGameEvent& e)
{
    return {
        .Delay = e.GetInt("delay"),
        .Reason = e.GetInt("reason"),
    };
}

HltvReplayStatus HltvReplayStatus::From(IGameEvent& e)
{
    return {
        .Reason = e.GetInt("reason"),
    };
}

HltvStatus HltvStatus::From(IGameEvent& e)
{
    return {
        .Clients = e.GetInt("clients"),
        .Slots = e.GetInt("slots"),
        .Proxies = e.GetInt("proxies"),
        .Master = e.GetString("master", ""),
    };
}

HltvTitle HltvTitle::From(IGameEvent& e)
{
    return {
        .Text = e.GetString("text", ""),
    };
}

HltvVersioninfo HltvVersioninfo::From(IGameEvent& e)
{
    return {
        .Version = e.GetInt("version"),
    };
}

HostageCallForHelp HostageCallForHelp::From(IGameEvent& e)
{
    return {
        .Hostage = e.GetInt("hostage"),
    };
}

HostageFollows HostageFollows::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Hostage = e.GetInt("hostage"),
    };
}

HostageHurt HostageHurt::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Hostage = e.GetInt("hostage"),
    };
}

HostageKilled HostageKilled::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Hostage = e.GetInt("hostage"),
    };
}

HostageRescued HostageRescued::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Hostage = e.GetInt("hostage"),
        .Site = e.GetInt("site"),
    };
}

HostageRescuedAll HostageRescuedAll::From(IGameEvent&)
{
    return {};
}

HostageStopsFollowing HostageStopsFollowing::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Hostage = e.GetInt("hostage"),
    };
}

HostnameChanged HostnameChanged::From(IGameEvent& e)
{
    return {
        .Hostname = e.GetString("hostname", ""),
    };
}

InfernoExpire InfernoExpire::From(IGameEvent& e)
{
    return {
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

InfernoExtinguish InfernoExtinguish::From(IGameEvent& e)
{
    return {
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

InfernoStartburn InfernoStartburn::From(IGameEvent& e)
{
    return {
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

InspectWeapon InspectWeapon::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

InstructorCloseLesson InstructorCloseLesson::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .HintName = e.GetString("hint_name", ""),
    };
}

InstructorServerHintCreate InstructorServerHintCreate::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .HintName = e.GetString("hint_name", ""),
        .HintReplaceKey = e.GetString("hint_replace_key", ""),
        .HintTarget = e.GetInt("hint_target"),
        .HintActivatorUseridSlot = e.GetPlayerSlot("hint_activator_userid").Get(),
        .HintTimeout = e.GetInt("hint_timeout"),
        .HintIconOnscreen = e.GetString("hint_icon_onscreen", ""),
        .HintIconOffscreen = e.GetString("hint_icon_offscreen", ""),
        .HintCaption = e.GetString("hint_caption", ""),
        .HintActivatorCaption = e.GetString("hint_activator_caption", ""),
        .HintColor = e.GetString("hint_color", ""),
        .HintIconOffset = e.GetFloat("hint_icon_offset"),
        .HintRange = e.GetFloat("hint_range"),
        .HintFlags = e.GetInt("hint_flags"),
        .HintBinding = e.GetString("hint_binding", ""),
        .HintGamepadBinding = e.GetString("hint_gamepad_binding", ""),
        .HintAllowNodrawTarget = e.GetBool("hint_allow_nodraw_target"),
        .HintNooffscreen = e.GetBool("hint_nooffscreen"),
        .HintForcecaption = e.GetBool("hint_forcecaption"),
        .HintLocalPlayerOnly = e.GetBool("hint_local_player_only"),
    };
}

InstructorServerHintStop InstructorServerHintStop::From(IGameEvent& e)
{
    return {
        .HintName = e.GetString("hint_name", ""),
    };
}

InstructorStartLesson InstructorStartLesson::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .HintName = e.GetString("hint_name", ""),
        .HintTarget = e.GetInt("hint_target"),
        .VrMovementType = e.GetInt("vr_movement_type"),
        .VrSingleController = e.GetBool("vr_single_controller"),
        .VrControllerType = e.GetInt("vr_controller_type"),
    };
}

InventoryUpdated InventoryUpdated::From(IGameEvent&)
{
    return {};
}

ItemEquip ItemEquip::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Item = e.GetString("item", ""),
        .Defindex = e.GetInt("defindex"),
        .Canzoom = e.GetBool("canzoom"),
        .Hassilencer = e.GetBool("hassilencer"),
        .Issilenced = e.GetBool("issilenced"),
        .Hastracers = e.GetBool("hastracers"),
        .Weptype = e.GetInt("weptype"),
        .Ispainted = e.GetBool("ispainted"),
    };
}

ItemPickup ItemPickup::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Item = e.GetString("item", ""),
        .Silent = e.GetBool("silent"),
        .Defindex = e.GetInt("defindex"),
    };
}

ItemPickupFailed ItemPickupFailed::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Item = e.GetString("item", ""),
        .Reason = e.GetInt("reason"),
        .Limit = e.GetInt("limit"),
    };
}

ItemPickupSlerp ItemPickupSlerp::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Index = e.GetInt("index"),
        .Behavior = e.GetInt("behavior"),
    };
}

ItemPurchase ItemPurchase::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Team = static_cast<VoltMod::Team>(e.GetInt("team")),
        .Loadout = e.GetInt("loadout"),
        .Weapon = e.GetString("weapon", ""),
    };
}

ItemRemove ItemRemove::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Item = e.GetString("item", ""),
        .Defindex = e.GetInt("defindex"),
    };
}

ItemSchemaInitialized ItemSchemaInitialized::From(IGameEvent&)
{
    return {};
}

JointeamFailed JointeamFailed::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Reason = e.GetInt("reason"),
    };
}

LocalPlayerControllerTeam LocalPlayerControllerTeam::From(IGameEvent&)
{
    return {};
}

LocalPlayerPawnChanged LocalPlayerPawnChanged::From(IGameEvent&)
{
    return {};
}

LocalPlayerTeam LocalPlayerTeam::From(IGameEvent&)
{
    return {};
}

LootCrateOpened LootCrateOpened::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Type = e.GetString("type", ""),
    };
}

LootCrateVisible LootCrateVisible::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Subject = e.GetInt("subject"),
        .Type = e.GetString("type", ""),
    };
}

MapShutdown MapShutdown::From(IGameEvent&)
{
    return {};
}

MapTransition MapTransition::From(IGameEvent&)
{
    return {};
}

MatchEndConditions MatchEndConditions::From(IGameEvent& e)
{
    return {
        .Frags = e.GetInt("frags"),
        .MaxRounds = e.GetInt("max_rounds"),
        .WinRounds = e.GetInt("win_rounds"),
        .Time = e.GetInt("time"),
    };
}

MaterialDefaultComplete MaterialDefaultComplete::From(IGameEvent&)
{
    return {};
}

MbInputLockCancel MbInputLockCancel::From(IGameEvent&)
{
    return {};
}

MbInputLockSuccess MbInputLockSuccess::From(IGameEvent&)
{
    return {};
}

MolotovDetonate MolotovDetonate::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

NavBlocked NavBlocked::From(IGameEvent& e)
{
    return {
        .Area = e.GetInt("area"),
        .Blocked = e.GetBool("blocked"),
    };
}

NavGenerate NavGenerate::From(IGameEvent&)
{
    return {};
}

NextlevelChanged NextlevelChanged::From(IGameEvent& e)
{
    return {
        .Nextlevel = e.GetString("nextlevel", ""),
        .Mapgroup = e.GetString("mapgroup", ""),
        .Skirmishmode = e.GetString("skirmishmode", ""),
    };
}

OpenCrateInstr OpenCrateInstr::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Subject = e.GetInt("subject"),
        .Type = e.GetString("type", ""),
    };
}

OtherDeath OtherDeath::From(IGameEvent& e)
{
    return {
        .Otherid = e.GetInt("otherid"),
        .Othertype = e.GetString("othertype", ""),
        .Attacker = e.GetInt("attacker"),
        .Weapon = e.GetString("weapon", ""),
        .WeaponItemid = e.GetString("weapon_itemid", ""),
        .WeaponFauxitemid = e.GetString("weapon_fauxitemid", ""),
        .WeaponOriginalownerXuid = e.GetString("weapon_originalowner_xuid", ""),
        .Headshot = e.GetBool("headshot"),
        .Penetrated = e.GetInt("penetrated"),
        .Noscope = e.GetBool("noscope"),
        .Thrusmoke = e.GetBool("thrusmoke"),
        .Attackerblind = e.GetBool("attackerblind"),
    };
}

ParachuteDeploy ParachuteDeploy::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

ParachutePickup ParachutePickup::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

PhysgunPickup PhysgunPickup::From(IGameEvent&)
{
    return {};
}

PlayerActivate PlayerActivate::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

PlayerAvengedTeammate PlayerAvengedTeammate::From(IGameEvent& e)
{
    return {
        .AvengerIdSlot = e.GetPlayerSlot("avenger_id").Get(),
        .AvengedPlayerIdSlot = e.GetPlayerSlot("avenged_player_id").Get(),
    };
}

PlayerBlind PlayerBlind::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .AttackerSlot = e.GetPlayerSlot("attacker").Get(),
        .Entityid = e.GetInt("entityid"),
        .BlindDuration = e.GetFloat("blind_duration"),
    };
}

PlayerChangename PlayerChangename::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Oldname = e.GetString("oldname", ""),
        .Newname = e.GetString("newname", ""),
    };
}

PlayerChat PlayerChat::From(IGameEvent& e)
{
    return {
        .Teamonly = e.GetBool("teamonly"),
        .Userid = e.GetInt("userid"),
        .Text = e.GetString("text", ""),
    };
}

PlayerConnect PlayerConnect::From(IGameEvent& e)
{
    return {
        .Name = e.GetString("name", ""),
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Networkid = e.GetString("networkid", ""),
        .Xuid = e.GetUint64("xuid"),
        .Bot = e.GetBool("bot"),
    };
}

PlayerConnectFull PlayerConnectFull::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

PlayerDeath PlayerDeath::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .AttackerSlot = e.GetPlayerSlot("attacker").Get(),
        .AssisterSlot = e.GetPlayerSlot("assister").Get(),
        .Assistedflash = e.GetBool("assistedflash"),
        .Weapon = e.GetString("weapon", ""),
        .WeaponItemid = e.GetString("weapon_itemid", ""),
        .WeaponFauxitemid = e.GetString("weapon_fauxitemid", ""),
        .WeaponOriginalownerXuid = e.GetString("weapon_originalowner_xuid", ""),
        .Headshot = e.GetBool("headshot"),
        .Dominated = e.GetInt("dominated"),
        .Revenge = e.GetInt("revenge"),
        .Wipe = e.GetInt("wipe"),
        .Penetrated = e.GetInt("penetrated"),
        .Noreplay = e.GetBool("noreplay"),
        .Noscope = e.GetBool("noscope"),
        .Thrusmoke = e.GetBool("thrusmoke"),
        .Attackerblind = e.GetBool("attackerblind"),
        .Distance = e.GetFloat("distance"),
        .DmgHealth = e.GetInt("dmg_health"),
        .DmgArmor = e.GetInt("dmg_armor"),
        .Hitgroup = static_cast<VoltMod::HitGroup>(e.GetInt("hitgroup")),
        .Attackerinair = e.GetBool("attackerinair"),
    };
}

PlayerDecal PlayerDecal::From(IGameEvent&)
{
    return {};
}

PlayerDisconnect PlayerDisconnect::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Reason = e.GetInt("reason"),
        .Name = e.GetString("name", ""),
        .Networkid = e.GetString("networkid", ""),
        .Xuid = e.GetUint64("xuid"),
        .PlayerID = e.GetInt("PlayerID"),
        .EverFullyConnected = e.GetBool("ever_fully_connected"),
    };
}

PlayerFalldamage PlayerFalldamage::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Damage = e.GetFloat("damage"),
    };
}

PlayerFootstep PlayerFootstep::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

PlayerFullUpdate PlayerFullUpdate::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Count = e.GetInt("count"),
    };
}

PlayerGivenC4 PlayerGivenC4::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

PlayerHintmessage PlayerHintmessage::From(IGameEvent& e)
{
    return {
        .Hintmessage = e.GetString("hintmessage", ""),
    };
}

PlayerHurt PlayerHurt::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .AttackerSlot = e.GetPlayerSlot("attacker").Get(),
        .Health = e.GetInt("health"),
        .Armor = e.GetInt("armor"),
        .Weapon = e.GetString("weapon", ""),
        .DmgHealth = e.GetInt("dmg_health"),
        .DmgArmor = e.GetInt("dmg_armor"),
        .Hitgroup = static_cast<VoltMod::HitGroup>(e.GetInt("hitgroup")),
    };
}

PlayerInfo PlayerInfo::From(IGameEvent& e)
{
    return {
        .Name = e.GetString("name", ""),
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Steamid = e.GetUint64("steamid"),
        .Bot = e.GetBool("bot"),
    };
}

PlayerJump PlayerJump::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

PlayerPing PlayerPing::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
        .Urgent = e.GetBool("urgent"),
    };
}

PlayerPingStop PlayerPingStop::From(IGameEvent& e)
{
    return {
        .Entityid = e.GetInt("entityid"),
    };
}

PlayerRadio PlayerRadio::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

PlayerResetVote PlayerResetVote::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Vote = e.GetBool("vote"),
    };
}

PlayerScore PlayerScore::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Kills = e.GetInt("kills"),
        .Deaths = e.GetInt("deaths"),
        .Score = e.GetInt("score"),
    };
}

PlayerShoot PlayerShoot::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Weapon = e.GetInt("weapon"),
        .Mode = e.GetInt("mode"),
    };
}

PlayerSound PlayerSound::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Radius = e.GetInt("radius"),
        .Duration = e.GetFloat("duration"),
        .Step = e.GetBool("step"),
    };
}

PlayerSpawn PlayerSpawn::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

PlayerSpawned PlayerSpawned::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Inrestart = e.GetBool("inrestart"),
    };
}

PlayerStatsUpdated PlayerStatsUpdated::From(IGameEvent& e)
{
    return {
        .Forceupload = e.GetBool("forceupload"),
    };
}

PlayerTeam PlayerTeam::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Team = static_cast<VoltMod::Team>(e.GetInt("team")),
        .Oldteam = static_cast<VoltMod::Team>(e.GetInt("oldteam")),
        .Disconnect = e.GetBool("disconnect"),
        .Silent = e.GetBool("silent"),
        .Isbot = e.GetBool("isbot"),
    };
}

RagdollDissolved RagdollDissolved::From(IGameEvent& e)
{
    return {
        .Entindex = e.GetInt("entindex"),
    };
}

ReadGameTitledata ReadGameTitledata::From(IGameEvent& e)
{
    return {
        .ControllerId = e.GetInt("controllerId"),
    };
}

RepostXboxAchievements RepostXboxAchievements::From(IGameEvent& e)
{
    return {
        .Splitscreenplayer = e.GetInt("splitscreenplayer"),
    };
}

ResetGameTitledata ResetGameTitledata::From(IGameEvent& e)
{
    return {
        .ControllerId = e.GetInt("controllerId"),
    };
}

RoundAnnounceFinal RoundAnnounceFinal::From(IGameEvent&)
{
    return {};
}

RoundAnnounceLastRoundHalf RoundAnnounceLastRoundHalf::From(IGameEvent&)
{
    return {};
}

RoundAnnounceMatchPoint RoundAnnounceMatchPoint::From(IGameEvent&)
{
    return {};
}

RoundAnnounceMatchStart RoundAnnounceMatchStart::From(IGameEvent&)
{
    return {};
}

RoundAnnounceWarmup RoundAnnounceWarmup::From(IGameEvent&)
{
    return {};
}

RoundEnd RoundEnd::From(IGameEvent& e)
{
    return {
        .Winner = e.GetInt("winner"),
        .Reason = e.GetInt("reason"),
        .Message = e.GetString("message", ""),
        .Legacy = e.GetInt("legacy"),
        .PlayerCount = e.GetInt("player_count"),
        .Nomusic = e.GetInt("nomusic"),
    };
}

RoundEndUploadStats RoundEndUploadStats::From(IGameEvent&)
{
    return {};
}

RoundFreezeEnd RoundFreezeEnd::From(IGameEvent&)
{
    return {};
}

RoundMvp RoundMvp::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Reason = e.GetInt("reason"),
        .Value = e.GetInt("value"),
        .Musickitmvps = e.GetInt("musickitmvps"),
        .Nomusic = e.GetInt("nomusic"),
        .Musickitid = e.GetInt("musickitid"),
    };
}

RoundOfficiallyEnded RoundOfficiallyEnded::From(IGameEvent&)
{
    return {};
}

RoundPoststart RoundPoststart::From(IGameEvent&)
{
    return {};
}

RoundPrestart RoundPrestart::From(IGameEvent&)
{
    return {};
}

RoundStart RoundStart::From(IGameEvent& e)
{
    return {
        .Timelimit = e.GetInt("timelimit"),
        .Fraglimit = e.GetInt("fraglimit"),
        .Objective = e.GetString("objective", ""),
    };
}

RoundStartPostNav RoundStartPostNav::From(IGameEvent&)
{
    return {};
}

RoundStartPreEntity RoundStartPreEntity::From(IGameEvent&)
{
    return {};
}

RoundTimeWarning RoundTimeWarning::From(IGameEvent&)
{
    return {};
}

SeasoncoinLevelup SeasoncoinLevelup::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Category = e.GetInt("category"),
        .Rank = e.GetInt("rank"),
    };
}

ServerCvar ServerCvar::From(IGameEvent& e)
{
    return {
        .Cvarname = e.GetString("cvarname", ""),
        .Cvarvalue = e.GetString("cvarvalue", ""),
    };
}

ServerMessage ServerMessage::From(IGameEvent& e)
{
    return {
        .Text = e.GetString("text", ""),
    };
}

ServerPreShutdown ServerPreShutdown::From(IGameEvent& e)
{
    return {
        .Reason = e.GetString("reason", ""),
    };
}

ServerShutdown ServerShutdown::From(IGameEvent& e)
{
    return {
        .Reason = e.GetString("reason", ""),
    };
}

ServerSpawn ServerSpawn::From(IGameEvent& e)
{
    return {
        .Hostname = e.GetString("hostname", ""),
        .Address = e.GetString("address", ""),
        .Port = e.GetInt("port"),
        .Game = e.GetString("game", ""),
        .Mapname = e.GetString("mapname", ""),
        .Addonname = e.GetString("addonname", ""),
        .Maxplayers = e.GetInt("maxplayers"),
        .Os = e.GetString("os", ""),
        .Dedicated = e.GetBool("dedicated"),
        .Password = e.GetBool("password"),
    };
}

SetInstructorGroupEnabled SetInstructorGroupEnabled::From(IGameEvent& e)
{
    return {
        .Group = e.GetString("group", ""),
        .Enabled = e.GetInt("enabled"),
    };
}

Sfuievent Sfuievent::From(IGameEvent& e)
{
    return {
        .Action = e.GetString("action", ""),
        .Data = e.GetString("data", ""),
        .Slot = e.GetInt("slot"),
    };
}

ShowDeathpanel ShowDeathpanel::From(IGameEvent& e)
{
    return {
        .VictimSlot = e.GetPlayerSlot("victim").Get(),
        .KillerControllerSlot = e.GetPlayerSlot("killer_controller").Get(),
        .HitsTaken = e.GetInt("hits_taken"),
        .DamageTaken = e.GetInt("damage_taken"),
        .HitsGiven = e.GetInt("hits_given"),
        .DamageGiven = e.GetInt("damage_given"),
    };
}

ShowSurvivalRespawnStatus ShowSurvivalRespawnStatus::From(IGameEvent& e)
{
    return {
        .LocToken = e.GetString("loc_token", ""),
        .Duration = e.GetInt("duration"),
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

SilencerDetach SilencerDetach::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

SilencerOff SilencerOff::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

SilencerOn SilencerOn::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

SmokeBeaconParadrop SmokeBeaconParadrop::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Paradrop = e.GetInt("paradrop"),
    };
}

SmokegrenadeDetonate SmokegrenadeDetonate::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

SmokegrenadeExpired SmokegrenadeExpired::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

SpecModeUpdated SpecModeUpdated::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

SpecTargetUpdated SpecTargetUpdated::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

StartHalftime StartHalftime::From(IGameEvent&)
{
    return {};
}

StartVote StartVote::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Type = e.GetInt("type"),
        .VoteParameter = e.GetInt("vote_parameter"),
    };
}

StorePricesheetUpdated StorePricesheetUpdated::From(IGameEvent&)
{
    return {};
}

SurvivalAnnouncePhase SurvivalAnnouncePhase::From(IGameEvent& e)
{
    return {
        .Phase = e.GetInt("phase"),
    };
}

SurvivalNoRespawnsFinal SurvivalNoRespawnsFinal::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

SurvivalNoRespawnsWarning SurvivalNoRespawnsWarning::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

SurvivalParadropBreak SurvivalParadropBreak::From(IGameEvent& e)
{
    return {
        .Entityid = e.GetInt("entityid"),
    };
}

SurvivalParadropSpawn SurvivalParadropSpawn::From(IGameEvent& e)
{
    return {
        .Entityid = e.GetInt("entityid"),
    };
}

SurvivalTeammateRespawn SurvivalTeammateRespawn::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

SwitchTeam SwitchTeam::From(IGameEvent& e)
{
    return {
        .NumPlayers = e.GetInt("numPlayers"),
        .NumSpectators = e.GetInt("numSpectators"),
        .AvgRank = e.GetInt("avg_rank"),
        .NumTSlotsFree = e.GetInt("numTSlotsFree"),
        .NumCTSlotsFree = e.GetInt("numCTSlotsFree"),
    };
}

TagrenadeDetonate TagrenadeDetonate::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Entityid = e.GetInt("entityid"),
        .X = e.GetFloat("x"),
        .Y = e.GetFloat("y"),
        .Z = e.GetFloat("z"),
    };
}

TeamInfo TeamInfo::From(IGameEvent& e)
{
    return {
        .Teamid = e.GetInt("teamid"),
        .Teamname = e.GetString("teamname", ""),
    };
}

TeamIntroEnd TeamIntroEnd::From(IGameEvent&)
{
    return {};
}

TeamIntroStart TeamIntroStart::From(IGameEvent&)
{
    return {};
}

TeamScore TeamScore::From(IGameEvent& e)
{
    return {
        .Teamid = e.GetInt("teamid"),
        .Score = e.GetInt("score"),
    };
}

TeamchangePending TeamchangePending::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Toteam = e.GetInt("toteam"),
    };
}

TeamplayBroadcastAudio TeamplayBroadcastAudio::From(IGameEvent& e)
{
    return {
        .Team = static_cast<VoltMod::Team>(e.GetInt("team")),
        .Sound = e.GetString("sound", ""),
    };
}

TeamplayRoundStart TeamplayRoundStart::From(IGameEvent& e)
{
    return {
        .FullReset = e.GetBool("full_reset"),
    };
}

TournamentReward TournamentReward::From(IGameEvent& e)
{
    return {
        .Defindex = e.GetInt("defindex"),
        .Totalrewards = e.GetInt("totalrewards"),
        .Accountid = e.GetInt("accountid"),
    };
}

TrialTimeExpired TrialTimeExpired::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

UgcFileDownloadFinished UgcFileDownloadFinished::From(IGameEvent& e)
{
    return {
        .Hcontent = e.GetUint64("hcontent"),
    };
}

UgcFileDownloadStart UgcFileDownloadStart::From(IGameEvent& e)
{
    return {
        .Hcontent = e.GetUint64("hcontent"),
        .PublishedFileId = e.GetUint64("published_file_id"),
    };
}

UgcMapDownloadError UgcMapDownloadError::From(IGameEvent& e)
{
    return {
        .PublishedFileId = e.GetUint64("published_file_id"),
        .ErrorCode = e.GetInt("error_code"),
    };
}

UgcMapInfoReceived UgcMapInfoReceived::From(IGameEvent& e)
{
    return {
        .PublishedFileId = e.GetUint64("published_file_id"),
    };
}

UgcMapUnsubscribed UgcMapUnsubscribed::From(IGameEvent& e)
{
    return {
        .PublishedFileId = e.GetUint64("published_file_id"),
    };
}

UpdateMatchmakingStats UpdateMatchmakingStats::From(IGameEvent&)
{
    return {};
}

UserDataDownloaded UserDataDownloaded::From(IGameEvent&)
{
    return {};
}

VipEscaped VipEscaped::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

VipKilled VipKilled::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .AttackerSlot = e.GetPlayerSlot("attacker").Get(),
    };
}

VoteCast VoteCast::From(IGameEvent& e)
{
    return {
        .VoteOption = e.GetInt("vote_option"),
        .Team = static_cast<VoltMod::Team>(e.GetInt("team")),
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

VoteCastNo VoteCastNo::From(IGameEvent& e)
{
    return {
        .Team = static_cast<VoltMod::Team>(e.GetInt("team")),
        .Entityid = e.GetInt("entityid"),
    };
}

VoteCastYes VoteCastYes::From(IGameEvent& e)
{
    return {
        .Team = static_cast<VoltMod::Team>(e.GetInt("team")),
        .Entityid = e.GetInt("entityid"),
    };
}

VoteChanged VoteChanged::From(IGameEvent& e)
{
    return {
        .VoteOption1 = e.GetInt("vote_option1"),
        .VoteOption2 = e.GetInt("vote_option2"),
        .VoteOption3 = e.GetInt("vote_option3"),
        .VoteOption4 = e.GetInt("vote_option4"),
        .VoteOption5 = e.GetInt("vote_option5"),
        .PotentialVotes = e.GetInt("potentialVotes"),
    };
}

VoteEnded VoteEnded::From(IGameEvent&)
{
    return {};
}

VoteFailed VoteFailed::From(IGameEvent& e)
{
    return {
        .Team = static_cast<VoltMod::Team>(e.GetInt("team")),
    };
}

VoteOptions VoteOptions::From(IGameEvent& e)
{
    return {
        .Count = e.GetInt("count"),
        .Option1 = e.GetString("option1", ""),
        .Option2 = e.GetString("option2", ""),
        .Option3 = e.GetString("option3", ""),
        .Option4 = e.GetString("option4", ""),
        .Option5 = e.GetString("option5", ""),
    };
}

VotePassed VotePassed::From(IGameEvent& e)
{
    return {
        .Details = e.GetString("details", ""),
        .Param1 = e.GetString("param1", ""),
        .Team = static_cast<VoltMod::Team>(e.GetInt("team")),
    };
}

VoteStarted VoteStarted::From(IGameEvent& e)
{
    return {
        .Issue = e.GetString("issue", ""),
        .Param1 = e.GetString("param1", ""),
        .Team = static_cast<VoltMod::Team>(e.GetInt("team")),
        .Initiator = e.GetInt("initiator"),
    };
}

WarmupEnd WarmupEnd::From(IGameEvent&)
{
    return {};
}

WeaponFire WeaponFire::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Weapon = e.GetString("weapon", ""),
        .Silenced = e.GetBool("silenced"),
    };
}

WeaponFireOnEmpty WeaponFireOnEmpty::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Weapon = e.GetString("weapon", ""),
    };
}

WeaponReload WeaponReload::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

WeaponZoom WeaponZoom::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

WeaponZoomRifle WeaponZoomRifle::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
    };
}

WeaponhudSelection WeaponhudSelection::From(IGameEvent& e)
{
    return {
        .Slot = e.GetPlayerSlot("userid").Get(),
        .Mode = e.GetInt("mode"),
        .Entindex = e.GetInt("entindex"),
    };
}

WriteGameTitledata WriteGameTitledata::From(IGameEvent& e)
{
    return {
        .ControllerId = e.GetInt("controllerId"),
    };
}

WriteProfileData WriteProfileData::From(IGameEvent&)
{
    return {};
}

}  // namespace VoltMod
