#pragma once

#include <optional>
#include <string>
#include <string_view>
#include <vector>

namespace CS2Kit::Core
{

/** One entry from a manifest's `dependencies` array. */
struct PluginDependency
{
    /** Addon name of the peer plugin, matching its own manifest `name`. */
    std::string Name;
    /** Lowest acceptable peer version, or empty when any version will do. */
    std::string MinVersion;
    /** true aborts the load when unsatisfied; false only warns. */
    bool Required = false;
};

/**
 * @brief What a plugin declares about itself, generated by cs2_add_plugin and installed
 * to `addons/<name>/<name>.manifest.json`.
 *
 * It exists on disk rather than compiled in so deploy tooling can inspect a bundle without
 * loading it. Nothing here is trusted for behaviour - it drives diagnostics only.
 */
struct PluginManifest
{
    std::string Name;
    std::string Version;
    std::string Description;
    std::vector<PluginDependency> Dependencies;
};

/** Parse manifest JSON. nullopt on malformed input or a missing required field. */
std::optional<PluginManifest> ParsePluginManifest(std::string_view json);

/**
 * Compare dotted-numeric versions, ignoring any `+build` or `-suffix` tail.
 * A missing component reads as zero, so "1.2" satisfies "1.2.0". An empty @p want
 * is satisfied by anything; a @p have that parses to nothing satisfies nothing.
 */
bool VersionAtLeast(std::string_view have, std::string_view want);

/**
 * @brief The identity a plugin publishes so peers can tell it is loaded and which version.
 *
 * Keyed by IdentityKey(name) rather than a fixed interface name, since the plugin name is
 * the part a dependant looks up. Only a `const char*` crosses the module boundary.
 */
struct IPluginIdentity
{
    virtual const char* PluginVersion() const = 0;

protected:
    ~IPluginIdentity() = default;
};

/** ServiceExchange key under which @p pluginName publishes its IPluginIdentity. */
std::string IdentityKey(std::string_view pluginName);

/**
 * @brief Holds this plugin's manifest, announces it to peers, and reports unmet dependencies.
 *
 * Owned by Services, so the published pointer stays valid for exactly one load cycle.
 *
 * Dependency checking is deliberately advisory. Metamod loads .vdf files in an order no
 * plugin controls, so at OnLoad time a peer that loads later is indistinguishable from one
 * that is not installed - checking then would report confident nonsense. The check is
 * therefore deferred to the first game frame, by which point every .vdf has loaded, and it
 * only logs: `Required` raises the message from a warning to an error rather than aborting.
 * Code that actually needs a peer still has to handle a null from ServiceExchange::Get at
 * the call site, which works no matter when the peer arrives or leaves.
 */
class PluginIdentity final : public IPluginIdentity
{
public:
    /** Take ownership of @p manifest, publish it under IdentityKey(manifest.Name), and queue
     *  the dependency report for the first game frame. */
    void Adopt(PluginManifest manifest);
    /** Stop answering peer lookups. Called during Shutdown. */
    void Withdraw();

    /** What this plugin declared, or an empty manifest when it ships none. */
    const PluginManifest& Manifest() const { return _manifest; }

    const char* PluginVersion() const override { return _manifest.Version.c_str(); }

private:
    PluginManifest _manifest;
    std::string _key;
};

}  // namespace CS2Kit::Core
