#pragma once

#include <optional>
#include <string>
#include <string_view>
#include <vector>

namespace VoltMod::Core
{

/** One entry from a manifest's `dependencies` array. */
struct PluginDependency
{
    /** Addon name of the peer, matching its own manifest `name`. */
    std::string Name;
    /** Lowest acceptable peer version; empty accepts any. */
    std::string MinVersion;
    /** Logs an error rather than a warning when unsatisfied. Neither aborts the load. */
    bool Required = false;
};

/**
 * @brief What a plugin declares about itself, generated by voltmod_add_plugin into
 * `addons/<name>/<name>.manifest.json`.
 *
 * On disk rather than compiled in so deploy tooling can inspect a bundle without loading
 * it. Diagnostics only - nothing here changes behaviour.
 */
struct PluginManifest
{
    std::string Name;
    std::string Version;
    std::string Description;
    std::vector<PluginDependency> Dependencies;
};

/** Parse manifest JSON. nullopt when malformed or nameless. */
std::optional<PluginManifest> ParsePluginManifest(std::string_view json);

/** Dotted-numeric compare, ignoring any `+build` or `-suffix` tail. Missing components read
 *  as zero, so "1.2" satisfies "1.2.0". Empty @p want accepts anything; an unparsable
 *  @p have satisfies nothing. */
bool VersionAtLeast(std::string_view have, std::string_view want);

/** Published by each plugin so peers can see it is loaded and at which version. Keyed by
 *  IdentityKey(name), since the name is what a dependant looks up. */
struct IPluginIdentity
{
    virtual const char* PluginVersion() const = 0;

protected:
    ~IPluginIdentity() = default;
};

/** ServiceExchange key under which @p pluginName publishes its IPluginIdentity. */
std::string IdentityKey(std::string_view pluginName);

}  // namespace VoltMod::Core
